### ISSUE TITLE
[Feature Request] Support filament changes?

### ISSUE THREAD

**Issue by abrenoch** [OllisGit/OctoPrint-SpoolManager#130]
It would be really nice if we had the opportunity to swap out the filament being used if an M600 event occurs. One would need the 'printer notifications' working it seems - this would give users the chance to select the new filament when octoprint prompts the user. Though this would all come down to how exactly the weight of the job is being calculated - obviously you would need to be able to determine how much filament was used up to and then after the M600.

Not sure how realistic that is, but wanted to toss the idea out there!

**Comment by abc2006** [comment]
+1 for me :)

**Comment by mukamuk1** [comment]
+1

**Comment by MrDragon420** [comment]
FOR SURE

**Comment by codingcatgirl** [comment]
Hey, as part of my pull request for Multi-Material support i've added the option to change the filament mid-print: #161 Please check out of that works for you :)

**Comment by Poporacer** [comment]
@codingcatgirl How can I load your version of the plugin to test?

**Comment by OllisGit** [comment]
@Poporacer go to the plugin-manager and enter this url:
https://github.com/codingcatgirl/OctoPrint-SpoolManager/archive/refs/heads/multi-material.zip

I am currently reviewing the PR. It looks really really good, so I think it will be merge in the next days.
It will take some time to review, because @codingcatgirl  and myself did a lot of changes in the sourcecode.
