### ISSUE TITLE
When starting a print, the selected spool from Spool manager shows initial total spool weight not current spool weight

### ISSUE THREAD

**Issue by clarkiej** [OllisGit/OctoPrint-SpoolManager#178]
Previous versions showed current spool weight when selecting the spool for printing. For V1.4.3, now when you select the spool the spool choice shows the initial spool weight (1000 gms) instead of the current spool weight (854 gms) as it did previously. It makes it difficult to choose spools if you have more than one spool of the same type/colour of differing remains in your spool catalogue.

**Comment by OllisGit** [comment]
@clarkiej please attach a screenshot of the selected spool-dialog and also the popup.
Btw. the poup before print, shows the same weight as in the selection-box, rigth?

**Comment by clarkiej** [comment]
Correct. It is just when you select the spool it now shows "Grey PLA (1000gm)" when previous it showed "Grey PLA (670gm)". Once selected it shows the remaining filament. I will do a screenshot once my current print finishes. Kieran ClarkeMobile +61418940005On 28 May 2021 05:53, OllisGit ***@***.***> wrote:
@clarkiej please attach a screenshot of the selected spool-dialog and also the popup.
Btw. the poup before print, shows the same weight as in the selection-box, rigth?

**Comment by codingcatgirl** [comment]
I might have the same problem here, but it looks different. There is different data displayed for the same spool. I'm not shown the initial weight of the spool but something is definitely wrong
![Bildschirmfoto von 2021-05-28 12-56-35](https://user-images.githubusercontent.com/3868507/119974004-78678200-bfb4-11eb-9520-a836ebd9bc39.png)

- The print i'm trying to start uses 58g of filament so… it doesn't make sense to be related to that.
- I do not have a spool that currently has 276g left, so it can't be mistaking it for a different spool.

In loadSpoolsByQuery, the following data is returned:
```
      "remainingLength": "-256064",
      "remainingLengthPercentage": "",
      "remainingPercentage": "19.2",
      "remainingWeight": "191.8",
```

but then, in the allowedToPrint call, the following data is returned:
```
    "reminderSpoolSelection": [
      {
        "bedOffset": null,
        "enclosureOffset": null,
        "material": "PETG",
        "remainingWeight": 276.3485105427127,
        "spoolName": "Prusament Jet Black 3",
        "toolIndex": 0,
        "toolOffset": null
      }
    ]
```

If i try to edit the spool, the value displayed it 191.8, so i assume that's the correct one… or is it?

The key difference seems to be that loadSpoolsByQuery runs it through transformSpoolModelToDict, and allowedToPrint doesn't. allowedToPrint calculates the remaining weight based on the total and used values from the database, while allowedToPrint just reads the remaining value from the database. That might cause an inconsistency, but it makes me wonder… why is the remaining value not in sync with the value of total weight and used weight? Could there be something wrong with how the multi-tool code commits the usage data to the database?

I don't know what your database is supposed to hold and store precisely, so it's for you to find out @OllisGit :) Hope this helps.

PS: Wondering if this might be ralted to #175 but it probably isn't.

**Comment by codingcatgirl** [comment]
Ok, i had toi look some more into it:

The culprit is here:
https://github.com/OllisGit/OctoPrint-SpoolManager/blob/master/octoprint_SpoolManager/__init__.py#L377

After the print, only used filament is updated, not remaining filament. And i'm to blame, since this code was introduced by my pull request.

Question: why are used filament and remaining filament stored as seperate values at all. Wouldn't it be a good idea to drop one of them from the database and always calculate it and if the user puts in a new value, just convert it into a new value for used filament instead?

**Comment by codingcatgirl** [comment]
Okay, apparently i'm no to blame after all, because before my edits, the previous code also didn't update the remainingWeight field: https://github.com/OllisGit/OctoPrint-SpoolManager/blob/45f730b0df7c29d8cd44e895cdbe143a776990b4/octoprint_SpoolManager/__init__.py#L328 So something else must be going on?

It looks like you just mistakenly added code to read the remainingWeight value from the spool model isntead of calculating it:
https://github.com/OllisGit/OctoPrint-SpoolManager/commit/3dbd15c429d4853f79a7eae2686ea71b6c300cae#diff-4963735b757dd922fea5143ec41a3b92d3464e9d242cbc11f8f243f716bc303aR324

Which is an easy mistake to make, since it seems like an obvious thing to do, but that begs the question even more why that field exists if you are not supposed to read data from it?

**Comment by clarkiej** [comment]
Update:

 

This is only happening with a new spool I added AFTER I performed the update:

 



 

With a spool in the system prior to the update, it displays correctly:

**Comment by clarkiej** [comment]
Update:

This is only happening with a new spool I added AFTER I performed the update:
![image](https://user-images.githubusercontent.com/81622030/120040440-2452b100-c039-11eb-85d4-c3d6c33a0158.png)

  
![image](https://user-images.githubusercontent.com/81622030/120040451-29176500-c039-11eb-8286-08110493544b.png)


With a spool in the system prior to the update, it displays correctly:

  
![image](https://user-images.githubusercontent.com/81622030/120040464-2e74af80-c039-11eb-92fc-dda10768d7f1.png)
![image](https://user-images.githubusercontent.com/81622030/120040479-35032700-c039-11eb-97e7-e59984510519.png)

**Comment by clarkiej** [comment]
Update.: If the spool weight is left blank, the spool weight does display when you go to start a print, BUT, the spool weight shown is the spool weight remaining after the previous print -n. It has not updated the total remaining after the previous print, but the filament remaining displayed in the spool catalogue is correct:

![image](https://user-images.githubusercontent.com/81622030/120081722-925aaf00-c0f1-11eb-8321-5c99fa15c2df.png)

Filament remaining in spool catalogue showing correctly.

Start the next print and the filament remaining is the amount that was left at the START of the previous print, not the end:

![image](https://user-images.githubusercontent.com/81622030/120081801-f5e4dc80-c0f1-11eb-8eb2-c87cc1027b54.png)

**Comment by clarkiej** [comment]
Olli,

 

The new release is working great.

I especially like the new picklist format. It looks sweet

 

Regards,

 

Kieran Clarke
