### ISSUE TITLE
Software no longer updates filament consumption Err Says missing metadata or spool-feilds.

### ISSUE THREAD

**Issue by chemixt** [OllisGit/OctoPrint-SpoolManager#280]
Ever since I updated beyond 1.4.3, The spool manager no longer shows any consumption of filament in the data file. I receive this message every time I print.

I have installed the latest Spool Manager, (SpoolManager Plugin (1.7.0) and still does not work.

I am using a MakerBot replicator 2X. on Octoprint Version 1.7.3

**" Octopi.local says:
Attention: Needed filament could not calculated (Missing
metadata or spool-fields)
There are no spools selected for the following tools dispite them
being used (maybe) by this print

Tool 0
Tool 1** "

This was originally opened as #218 (ERROR MESSAGE when printing), but was closed without a resolution.

Update 5-23-2022 - now running Octoprint 1.8, but still same problem

**Comment by WhiskeySheppard** [comment]
I keep getting this same error randomly. Previously I used to be able to just remove the spool, restart octoprint then add the spool back and start printing. Now it just works when it wants to and too but too frequently when all I'm trying to do is start a simple print and end up having to waste time restarting printer, Computer running octoprint with my fingers crossed hoping this plugin will decide to work as intended instead of being the cause for wasting my time and preventing me simply using my 3D printer. 
doing research, I seen where this was recommended:

Analyze gcode for time and model size estimates
Always
Only when idle (not printing)
Never

With always selected but still experiencing this issue too frequently preventing me from printing. Any suggestions?
