### ISSUE TITLE
Required Filament unknown for new files added via watched folder

### ISSUE THREAD

**Issue by MrSco** [OllisGit/OctoPrint-SpoolManager#292]
reboot/restart octoprint required for 'Required Filament unknown' message to be resolved on new print files added via watched folder. after reboot, required filament is calculated and clicking print doesn't give warning that 'required filament unknown'.

**Comment by PowerShellCrack** [comment]
I am having the same issue except even after reboot I still get 'required filament unknown' no matter what I do. I believe this is coming from cost estimator plugin though. But both the cost estimator and print job history are selected to use spool manager.  I did have the older plugin filament manager installed and if I select that it would work just fine, but I have fully migrated to this one because if its detailed settings. 
![image](https://user-images.githubusercontent.com/20599825/197920311-675c0600-1e83-4db8-bddb-4304f7dab2ee.png)

![image](https://user-images.githubusercontent.com/20599825/197918939-2ae6a081-761e-45e9-a06e-aed6298244a4.png)

![image](https://user-images.githubusercontent.com/20599825/197919257-ab165624-6ed3-4de7-abb1-0d36c33473d9.png)

![image](https://user-images.githubusercontent.com/20599825/197919394-77756c34-f50e-471d-a8ed-092294844d2e.png)

Printer: Anet A6
OctoPrint: 1.8.6
Python: 3.7.3
OctoPi: 0.18.0
Cost Estimator plugin: 3.5.0
Spool Manager plugin: 1.7.0
Print Job History plugin: 1.17.0

**Comment by PowerShellCrack** [comment]
I found that if I uninstall the PrintGeniusPlugin, this fixes the issue.
