### ISSUE TITLE
[REQUEST] If a new spool is created then add the color and material to the filtered view if not already included.

### ISSUE THREAD

**Issue by gohma231** [OllisGit/OctoPrint-SpoolManager#309]
I'm not actually sure if this is intended behavior: If a spool is created that does not have a matching material and color, the color and material are not automatically added to the filtered view.

**Comment by mdziekon** [comment]
Hi @gohma231, I've recently fixed this issue (I considered this behavior as mostly annoying, at least when "Select all" filter was checked) in my fork of this plugin: https://github.com/mdziekon/OctoPrint-SpoolManager/pull/15

If you're still interested and still using this plugin, you can use my fork instead of the original one (judging by the activity, looks like the original is dead). Since it's not published to OctoPrint's repo, unfortunately, you'll have to package it yourself (zip the entire plugin's code folder) and install it manually (via file upload).
