### ISSUE TITLE
Is this dead? 

### ISSUE THREAD

**Issue by WoosterInitiative** [OllisGit/OctoPrint-SpoolManager#333]
It doesn't look like this has been touched since March 2022, more than a year ago. It doesn't seem to want to install on Ubuntu jammy, at least for me, and I'm not sure whether it's worth trying to figure it out

**Comment by darthbeluga** [comment]
I am trying to do the same. I was just wondering that as well.

**Comment by CobraA1** [comment]
Looks like OllisGit has been pretty inactive the past year or so, only 9 commits (none to this particular project) in the last year.

It still works, I've been using it. But it looks like a few bugs are unlikely to be resolved.

**Comment by wizardkitty** [comment]
OllisGit Maintains the only Two filament mangers for octoprint. both are now effectively abandoned with basically the same issue. If anyone could fix it that would be welcome.

**Comment by mdziekon** [comment]
@wizardkitty take a look at my fork of this plugin: https://github.com/mdziekon/OctoPrint-SpoolManager

Recently I've been fixing some performance issues I had with my OctoPrint instance, did some fixes to this plugin as well, but since it's effectively dead (as in, development is dead, not the plugin itself which works rather fine), I've been pushing every change to my fork only. It's not much, I won't promise to fix every issue there is with this plugin, but I guess it's the closest thing to maintenance you can get at this moment.

**Comment by wizardkitty** [comment]
@mdziekon Well. The same person also maintained the filament manager plugin and it seems both have run into the same issue of installation and its only going to get worse with time as other linux distros get updated. Ill probably look into reporting both of these plugins as abandoned in a couple weeks if no response is given to this issue or the one in filament manager asking if its been abandoned.

**Comment by Kehet** [comment]
@OllisGit seems to be alive 🎉

https://github.com/OctoPrint/plugins.octoprint.org/issues/1213#issuecomment-1647442098

**Comment by Kehet** [comment]
bump

**Comment by dimo414** [comment]
@OllisGit says they're [still here](https://github.com/OctoPrint/plugins.octoprint.org/issues/1213#issuecomment-1647442098). 

OllisGit, if you see this it would be _amazing_ if you could turn off the auto-close GitHub action on your repos.  I understand you can't respond to everything immediately but in the meantime the auto-closer is causing harm.

(Edit: I missed the comment above linking to the same post - leaving this comment here since the auto-closer is still a problem)

**Comment by dimo414** [comment]
.

**Comment by flaviut** [comment]
.

**Comment by challgren** [comment]
.

**Comment by gbeatty** [comment]
bump

**Comment by drohhyn** [comment]
The addon was taken over, have a look here: https://github.com/dojohnso/OctoPrint-SpoolManager
There is already a new version in the plugins repo.

**Comment by ThomDietrich** [comment]
Any recommendation which fork to go with?
Seems like there are three considerably active forks:
- https://github.com/dojohnso/OctoPrint-SpoolManager by @dojohnso
- https://github.com/mdziekon/OctoPrint-SpoolManager by @mdziekon didn't see updates in 6 months
- https://github.com/jkotowicz1/OctoPrint-SpoolManager by @jkotowicz1, a fork from @mdziekon 's latest

Did you consider joining forces? You guys could form a GitHub organization and manage some of the abandoned repos under that :)

**Comment by Kehet** [comment]
@ThomDietrich [Octoprints plugin repo](https://plugins.octoprint.org/plugins/SpoolManager/) seems to point to https://github.com/dojohnso/OctoPrint-SpoolManager, so I think that would be considered official fork now

**Comment by ThomDietrich** [comment]
Still relevant. Let's keep this one active for updates on forks etc

**Comment by drohhyn** [comment]
> Still relevant. Let's keep this one active for updates on forks etc

No, it's not.
As already mentioned earlier, the plugin is still in the official repo under https://plugins.octoprint.org/plugins/SpoolManager/ AND it points to this github repo: https://github.com/dojohnso/OctoPrint-SpoolManager. Both links are in this discussion within the last 5 comments.

Updates on forks can be found in the forks, there is no more reason to have it here. The most relevant fork is the one from dojohnso because this repo builds the official plugins.

**Comment by ThomDietrich** [comment]
This repo does not seem properly maintained.
There is no harm in keeping this "information thread" open for future news/discussions. You don't have to care about it and may unsubscribe from the thread.
This is how GitHub works.

**Comment by drohhyn** [comment]
> This repo does not seem properly maintained.

I am not associated with the plugins maintainer in any way (but a user myself), but: last commit 4 days ago, several features branches + release + "official repo" as listed on octoprint.org.
> There is no harm in keeping this "information thread" open for future news/discussions.

Correct, but the question was "is this dead"? Answer: yes AND there is ONE relevant fork. This is the important info for all those coming from old plugin installations, thus this thread is answered and should be closed (which would have happened automatically). You can still find and build your preferred fork, but the official one is still https://github.com/dojohnso/OctoPrint-SpoolManager
> You don't have to care about it and may unsubscript from it

Done this already, because the answer is given several times.

**Comment by Ajimaru** [comment]
That worked for me on OctoPrint 1.9.3 Python 3.10.12 [https://github.com/OllisGit/OctoPrint-FilamentManager/issues/119#issuecomment-1624481946](url)

**Comment by ThomDietrich** [comment]
https://github.com/OctoPrint/plugins.octoprint.org/issues/1319
