### ISSUE TITLE
Feature request: change filament after print is started.. 

### ISSUE THREAD

**Issue by spanzetta** [OllisGit/OctoPrint-SpoolManager#76]
In case where you forget to select the right filament... make it possible to change (add an "edit" button) filament for a started or even finished print.. so the job history is properly updated
Before confirming there should be a message saying something like:
" Do you confirm you want to change the [Print name] print from [old filament] to [new filament]
This will will remove [print grams] from [old filament] and add it to [new filament]"
After this the filament database will be updated (print job history)

**Comment by OllisGit** [comment]
Hi @spanzetta ,

good idea!
I think the confirm-dialog should have more options. 
- As you mentioned: update both spools
- update only the old spool
- update only the new spool
- or do not update values just change the spool

But this feature should be placed in the PJH issue tracker, because you want to edit a print job and not a spool....and first: I need a direct SpoolManager-Integration....this is tracked here: https://github.com/OllisGit/OctoPrint-PrintJobHistory/issues/75

 PS. Sorry, for being late to the party, but I made a "Octoprint sabatical" (no coding, no printing) the last months.
